name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Show SDKs
        run: xcodebuild -showsdks
      - name: List available simulators
        run: xcrun simctl list
      - name: Build and test
        run: |
          xcodebuild test \
            -project build-a-bot/build-a-bot.xcodeproj \
            -scheme build-a-bot \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14' \
            CODE_SIGNING_ALLOWED=NO
