name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Use latest stable Xcode 15 release
          xcode-version: '15.4'
      - name: Build and run tests
        run: |
          xcodebuild test \
            -project build-a-bot/build-a-bot.xcodeproj \
            -scheme build-a-bot \
            -destination 'platform=iOS Simulator,name=iPhone 14'
